# Generated by Django 4.2.30 on 2026-08-24 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_seed_user_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=150)),
                ('requirements', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_executive', 'Pending Executive Review'), ('rejected_by_executive', 'Rejected by Executive'), ('pending_director', 'Pending Director Review'), ('rejected_by_director', 'Rejected by Director'), ('approved', 'Approved / In Development'), ('completed', 'Completed')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='accounts.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=150)),
                ('file_path', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketApproval',
            fields=[
                ('decision_id', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('decision_as', models.CharField(choices=[('executive_officer', 'Executive Officer'), ('it_director', 'IT Director')], max_length=50)),
                ('remark', models.TextField()),
                ('decision_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_decisions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='tickets.ticket')),
            ],
        ),
    ]
