# Generated by Django 4.2.30 on 2026-08-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_executive', 'Pending Executive Review'), ('rejected_by_executive', 'Rejected by Executive'), ('pending_director', 'Pending Director Review'), ('rejected_by_director', 'Rejected by Director'), ('approved', 'Approved / In Development'), ('completed', 'Completed'), ('closed', 'Closed')], default='draft', max_length=30),
        ),
    ]
