# Generated by Django 4.2.30 on 2026-09-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdocument',
            name='file_path',
            field=models.FileField(upload_to='tickets/'),
        ),
    ]
