# Generated by Django 4.2.30 on 2026-09-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticketdocument_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdocument',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdocument',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
