# Generated by Django 4.2.30 on 2026-09-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketdocument_file_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdocument',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketdocument',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
