# Generated by Django 4.2.30 on 2026-09-02 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketdocument_file_size_ticketdocument_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdocument',
            name='file_path',
        ),
    ]
